gcp_configuration_name=randomizer

# Where and how the app is deployed by gcloud_run_deploy.sh (utils-bash).
gcp_service=randomizer
gcp_region=us-central1
gcp_run_args=(
	--allow-unauthenticated
	--max-instances 2
)
